"""add_user_password

Revision ID: 4e86a5b1b1ef
Revises: 9142e129d955
Create Date: 2026-01-15 15:34:05.240257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4e86a5b1b1ef'
down_revision: Union[str, None] = '9142e129d955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('isCompleted', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'user', ['userId'], ['id'])
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'created_at')
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.add_column('tasks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'user', ['user_id'], ['id'])
    op.drop_column('tasks', 'userId')
    op.drop_column('tasks', 'updatedAt')
    op.drop_column('tasks', 'createdAt')
    op.drop_column('tasks', 'isCompleted')
    # ### end Alembic commands ###
